server:
  port: 8080
  
spring:
  application:
    name: spring-data-jpa-demo
    
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/parking_system
    platform: org.hibernate.dialect.PostgreSQLDialect
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update